//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoTools.Utils.Trad.Setting {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Theme {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Theme() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotoTools.Utils.Trad.Setting.Theme.Theme", typeof(Theme).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string BtAddNewThemeCancel {
            get {
                return ResourceManager.GetString("BtAddNewThemeCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        internal static string BtAddNewThemeValid {
            get {
                return ResourceManager.GetString("BtAddNewThemeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red:
        ///Green:
        ///Blue:
        ///Hexa:.
        /// </summary>
        internal static string ButtonThemeToolTip {
            get {
                return ResourceManager.GetString("ButtonThemeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme name cannot be empty.
        /// </summary>
        internal static string EmptyThemeNameMessage {
            get {
                return ResourceManager.GetString("EmptyThemeNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SaveFileTitle {
            get {
                return ResourceManager.GetString("SaveFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The theme &quot;{0}&quot; has been added.
        /// </summary>
        internal static string ThemeAddedMessage {
            get {
                return ResourceManager.GetString("ThemeAddedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred.
        ///Theme &quot;{0}&quot; was not deleted.
        /// </summary>
        internal static string ThemeDeleteFalseMessage {
            get {
                return ResourceManager.GetString("ThemeDeleteFalseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the &quot;{0}&quot; theme ?.
        /// </summary>
        internal static string ThemeDeleteQuestion {
            get {
                return ResourceManager.GetString("ThemeDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string ThemeDeleteTitleMessage {
            get {
                return ResourceManager.GetString("ThemeDeleteTitleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string ThemeDeleteTitleQuestion {
            get {
                return ResourceManager.GetString("ThemeDeleteTitleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The theme &quot;{0}&quot; was deleted.
        /// </summary>
        internal static string ThemeDeleteTrueMessage {
            get {
                return ResourceManager.GetString("ThemeDeleteTrueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but this theme is locked you can&apos;t modifed it.
        /// </summary>
        internal static string ThemeLockMessage {
            get {
                return ResourceManager.GetString("ThemeLockMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ThemeLockTitle {
            get {
                return ResourceManager.GetString("ThemeLockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &quot;{0}&quot; is already used.
        ///Please modify it.
        /// </summary>
        internal static string ThemeNameExistMessage {
            get {
                return ResourceManager.GetString("ThemeNameExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The theme &quot;{0}&quot; was not added.
        /// </summary>
        internal static string ThemeNotAddedMessage {
            get {
                return ResourceManager.GetString("ThemeNotAddedMessage", resourceCulture);
            }
        }
    }
}
